version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: go-backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
